title: HaxrByte â€” GhostShell Ops
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
color_scheme: dark
# plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-remote-theme]

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

baseurl: "/ghost-shell"

# Add a hook for custom CSS
include:
  - assets/css/custom.css
  
markdown: kramdown
kramdown:
  toc_levels: 1..3
